services:
  app:
    build: ./docker/app
    stdin_open: true
    tty: true
    volumes:
      - app:/app
    depends_on:
      - db
    command: '/run.sh'
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=my_app_network"
      - "traefik.http.services.my_app_app_service.loadbalancer.server.port=4000"
      - "traefik.http.routers.my_app_app_unsecure.rule=Host(`app.my-app.localhost`)"
      - "traefik.http.routers.my_app_app_unsecure.entrypoints=web"
      - "traefik.http.routers.my_app_app_unsecure.service=my_app_app_service"
      - "traefik.http.routers.my_app_app_unsecure.middlewares=my_app_app_secure_middleware"
      - "traefik.http.middlewares.my_app_app_secure_middleware.redirectscheme.scheme=https"
      - "traefik.http.routers.my_app_app_secure.entrypoints=web-ssl"
      - "traefik.http.routers.my_app_app_secure.rule=Host(`app.my-app.localhost`)"
      - "traefik.http.routers.my_app_app_secure.service=my_app_app_service"
      - "traefik.http.routers.my_app_app_secure.tls=true"

  db:
    image: postgres:16.3-alpine
    command: 'postgres -c "max_connections=200"'
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - type: volume
        source: postgres-data
        target: /var/lib/postgresql/data
        volume:
          nocopy: true
    labels:
      - "traefik.enable=true"
      - "traefik.docker.network=my_app_network"
      - "traefik.tcp.routers.my_app_db.rule=HostSNI(`db.my-app.localhost`)"
      - "traefik.tcp.routers.my_app_db.entryPoints=postgres"
      - "traefik.tcp.routers.my_app_db.tls=true"
      - "traefik.tcp.services.my_app_db_service.loadbalancer.server.port=5432"

  # Standalone container for npm handling
  assets:
    build:
      context: .
      dockerfile: docker/assets/Dockerfile
    working_dir: /app/assets
    volumes:
      - app:/app
    profiles:
      - tools

volumes:
  postgres-data:
  app:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: .

networks:
  default:
    name: my_app_network

