defmodule MyApp.Repo.Migrations.CreateRepresentatives do
  @moduledoc """
  Updates resources based on their most recent snapshots.

  This file was autogenerated with `mix ash_postgres.generate_migrations`
  """

  use Ecto.Migration

  def up do
    alter table(:tickets) do
      modify :representative_id, :uuid
    end

    create index(:tickets, [:representative_id])

    create table(:representatives, primary_key: false) do
      add :id, :uuid, null: false, default: fragment("gen_random_uuid()"), primary_key: true
      add :name, :text
    end
  end

  def down do
    drop table(:representatives)

    drop_if_exists index(:tickets, [:representative_id])

    alter table(:tickets) do
      modify :representative_id, :uuid
    end
  end
end
